apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rd-tech
  description: RD - RaiaDrogasil
  links:
    - url: http://rd.com.br/
      title: Website
    - url: https://rd-tech-archs.raiadrogasil.io/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: RD - RaiaDrogasil
    email: info@rd.com.br
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [tribe-microservices]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tribe-microservices
  description: Tribo Microservices
spec:
  type: tribe
  # Intentional no profile for testing
  parent: rd-tech
  children: [ms-order, ms-delivery]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ms-order
  description: MS Order
spec:
  type: squad
  profile:
    # Intentional no displayName for testing
    email: squadmsorder@rd.com.br
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: tribe-microservices
  hasMember: [halyson]
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ms-delivery
  description: MS Delivery
spec:
  type: squad
  profile:
    # Intentional no displayName for testing
    email: squadmsorder@rd.com.br
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: tribe-microservices
  hasMember: []
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: halyson
spec:
  profile:
    # Intentional no displayName for testing
    email: halyson@rd.com.br
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [ms-order]
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: order-domain
  description: Everything related to orders
spec:
  owner: ms-order
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ms-order-portal
  description: Everything related to order
  tags:
    - portal
spec:
  owner: ms-order
  domain: order-domain
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: order-api
  description: The Order API
  tags:
    - microservices
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: ms-order
  definition:
    $text: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: order-db
  description: Stores order information
spec:
  type: database
  owner: ms-order
  system: order-system
